// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMM9rprDq7gj6qYu-ZsQT0RZw-M4lDRzs',
    appId: '1:427521761302:web:caa64e9b8a9eb987dbd537',
    messagingSenderId: '427521761302',
    projectId: 'tictactoe-38469',
    authDomain: 'tictactoe-38469.firebaseapp.com',
    storageBucket: 'tictactoe-38469.firebasestorage.app',
    measurementId: 'G-X1NVCDKKVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1p5_cDTfrqxxS0OkpvuWYjsfY1HDuuOo',
    appId: '1:427521761302:android:f49d7ac89f56697bdbd537',
    messagingSenderId: '427521761302',
    projectId: 'tictactoe-38469',
    storageBucket: 'tictactoe-38469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC39fnFttaoAESsyJLP9u4CabmkcGXE2Q',
    appId: '1:427521761302:ios:c90c57a84946f87bdbd537',
    messagingSenderId: '427521761302',
    projectId: 'tictactoe-38469',
    storageBucket: 'tictactoe-38469.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC39fnFttaoAESsyJLP9u4CabmkcGXE2Q',
    appId: '1:427521761302:ios:c90c57a84946f87bdbd537',
    messagingSenderId: '427521761302',
    projectId: 'tictactoe-38469',
    storageBucket: 'tictactoe-38469.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMM9rprDq7gj6qYu-ZsQT0RZw-M4lDRzs',
    appId: '1:427521761302:web:2c0d4aaf8b67fe7cdbd537',
    messagingSenderId: '427521761302',
    projectId: 'tictactoe-38469',
    authDomain: 'tictactoe-38469.firebaseapp.com',
    storageBucket: 'tictactoe-38469.firebasestorage.app',
    measurementId: 'G-EEZZMN0ECY',
  );
}
