// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJcPAipF5Lzebexp1P9ogsFBjK7iTBDyc',
    appId: '1:331101018652:web:15030a0c6577bb7683ddd9',
    messagingSenderId: '331101018652',
    projectId: 'hypergaragesale-6eecd',
    authDomain: 'hypergaragesale-6eecd.firebaseapp.com',
    storageBucket: 'hypergaragesale-6eecd.firebasestorage.app',
    measurementId: 'G-9QRG4LMG9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCooVDS-Od_3ai4ycLYfQC0om3hMy6rfIY',
    appId: '1:331101018652:android:5bf4ec69d692e99b83ddd9',
    messagingSenderId: '331101018652',
    projectId: 'hypergaragesale-6eecd',
    storageBucket: 'hypergaragesale-6eecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiGmZRYjfpXIXutsxRB16Ll8vw4jDEo4',
    appId: '1:331101018652:ios:beeb1b1680e50aad83ddd9',
    messagingSenderId: '331101018652',
    projectId: 'hypergaragesale-6eecd',
    storageBucket: 'hypergaragesale-6eecd.firebasestorage.app',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiGmZRYjfpXIXutsxRB16Ll8vw4jDEo4',
    appId: '1:331101018652:ios:beeb1b1680e50aad83ddd9',
    messagingSenderId: '331101018652',
    projectId: 'hypergaragesale-6eecd',
    storageBucket: 'hypergaragesale-6eecd.firebasestorage.app',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJcPAipF5Lzebexp1P9ogsFBjK7iTBDyc',
    appId: '1:331101018652:web:34a4a8a22ededa4f83ddd9',
    messagingSenderId: '331101018652',
    projectId: 'hypergaragesale-6eecd',
    authDomain: 'hypergaragesale-6eecd.firebaseapp.com',
    storageBucket: 'hypergaragesale-6eecd.firebasestorage.app',
    measurementId: 'G-1PC8ZMV0MX',
  );
}
