// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUITtwceEIgUsbXds17My8qmQcGBx2_LI',
    appId: '1:97085075286:web:bbd81178d7a384f1e6f0f7',
    messagingSenderId: '97085075286',
    projectId: 'quiz-app-c4b29',
    authDomain: 'quiz-app-c4b29.firebaseapp.com',
    storageBucket: 'quiz-app-c4b29.firebasestorage.app',
    measurementId: 'G-YDHPXDN1W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTFtJQjoTS3SiMc43s9ZnlH-WroYyBVkI',
    appId: '1:97085075286:android:b158ba1dff80311ee6f0f7',
    messagingSenderId: '97085075286',
    projectId: 'quiz-app-c4b29',
    storageBucket: 'quiz-app-c4b29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5WUBDlueuRigKV2k3xucrJavVjGDyO2c',
    appId: '1:97085075286:ios:e6f8085060dc8856e6f0f7',
    messagingSenderId: '97085075286',
    projectId: 'quiz-app-c4b29',
    storageBucket: 'quiz-app-c4b29.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5WUBDlueuRigKV2k3xucrJavVjGDyO2c',
    appId: '1:97085075286:ios:e6f8085060dc8856e6f0f7',
    messagingSenderId: '97085075286',
    projectId: 'quiz-app-c4b29',
    storageBucket: 'quiz-app-c4b29.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUITtwceEIgUsbXds17My8qmQcGBx2_LI',
    appId: '1:97085075286:web:d3f40a8f1128a308e6f0f7',
    messagingSenderId: '97085075286',
    projectId: 'quiz-app-c4b29',
    authDomain: 'quiz-app-c4b29.firebaseapp.com',
    storageBucket: 'quiz-app-c4b29.firebasestorage.app',
    measurementId: 'G-65VTPXHKCG',
  );
}
