// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQlHIRuMvZtLXkIvYpaejDBKqxYyzfBc',
    appId: '1:738649819071:web:7896b95a47a3c3f001030a',
    messagingSenderId: '738649819071',
    projectId: 'flutter-ai-playground-af359',
    authDomain: 'flutter-ai-playground-af359.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-af359.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiUfXiIeOKlG2RdhuXHNXJ8Om0VI424D0',
    appId: '1:738649819071:android:427736404b9c4d4701030a',
    messagingSenderId: '738649819071',
    projectId: 'flutter-ai-playground-af359',
    storageBucket: 'flutter-ai-playground-af359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdoUuIfo_8VNhiAMKrLiHB1f6_pq9i6s',
    appId: '1:738649819071:ios:eda90d7446ef9cb301030a',
    messagingSenderId: '738649819071',
    projectId: 'flutter-ai-playground-af359',
    storageBucket: 'flutter-ai-playground-af359.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdoUuIfo_8VNhiAMKrLiHB1f6_pq9i6s',
    appId: '1:738649819071:ios:eda90d7446ef9cb301030a',
    messagingSenderId: '738649819071',
    projectId: 'flutter-ai-playground-af359',
    storageBucket: 'flutter-ai-playground-af359.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
