// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSf_X2IN1eV4QUGDnnIxhRdYr4TBnw_Q',
    appId: '1:391829980791:web:3c9e3f1c168f5b4510a872',
    messagingSenderId: '391829980791',
    projectId: 'camera-d8dde',
    authDomain: 'camera-d8dde.firebaseapp.com',
    storageBucket: 'camera-d8dde.firebasestorage.app',
    measurementId: 'G-TJTC9KE3DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80wL_qFFbQm2riNHdpZWrRehrlaKHukI',
    appId: '1:391829980791:android:a9aeac38c49c88f710a872',
    messagingSenderId: '391829980791',
    projectId: 'camera-d8dde',
    storageBucket: 'camera-d8dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQfPadVpdbvKChSfoArO-2Fpo6o2QDLU',
    appId: '1:391829980791:ios:11597d457e6666ac10a872',
    messagingSenderId: '391829980791',
    projectId: 'camera-d8dde',
    storageBucket: 'camera-d8dde.firebasestorage.app',
    iosBundleId: 'com.example.cameraExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQfPadVpdbvKChSfoArO-2Fpo6o2QDLU',
    appId: '1:391829980791:ios:11597d457e6666ac10a872',
    messagingSenderId: '391829980791',
    projectId: 'camera-d8dde',
    storageBucket: 'camera-d8dde.firebasestorage.app',
    iosBundleId: 'com.example.cameraExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeSf_X2IN1eV4QUGDnnIxhRdYr4TBnw_Q',
    appId: '1:391829980791:web:661085dc0acba81710a872',
    messagingSenderId: '391829980791',
    projectId: 'camera-d8dde',
    authDomain: 'camera-d8dde.firebaseapp.com',
    storageBucket: 'camera-d8dde.firebasestorage.app',
    measurementId: 'G-VFRJS7RLGL',
  );
}
