// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5LthGGnuejsOTkEUMlSVF7Izw5rO8tvE',
    appId: '1:287746447870:web:8e84a7cccc39f8a24b88af',
    messagingSenderId: '287746447870',
    projectId: 'todo-6e74b',
    authDomain: 'todo-6e74b.firebaseapp.com',
    storageBucket: 'todo-6e74b.firebasestorage.app',
    measurementId: 'G-8JXJM1QM6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxGF6BtFGC0wyKt6VWH6YC0UdC6G4Sw-8',
    appId: '1:287746447870:android:275f7ae71a7e9ebd4b88af',
    messagingSenderId: '287746447870',
    projectId: 'todo-6e74b',
    storageBucket: 'todo-6e74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ws2XDxxpHm0WZGxb7FNqeIMy86yBWsg',
    appId: '1:287746447870:ios:75e215f27832b74f4b88af',
    messagingSenderId: '287746447870',
    projectId: 'todo-6e74b',
    storageBucket: 'todo-6e74b.firebasestorage.app',
    iosBundleId: 'com.mycompany.todolist2024winter',
  );
}
